site_name: ""
site_url: https://khintz.github.io
site_dir: public
theme:
  name: material # readthedocs|mkdocs|material
  palette:
    # Palette for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    # Palette for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
  highlightjs: true
  hljs_languages:
      - yaml
      - rust
      - bash
  nav_style: dark
  features:
    - header.autohide
    - navigation.instant
    - navigation.sections
    - navigation.tracking
    - navigation.path
    - toc.follow
  logo: assets/logo.png
  favicon: images/favicon.png
  icon:
    admonition:
      info: octicons/info-16
nav:
 - Welcome: index.md
 - Personal:
    Publications: personal/publications.md
 - Topics:
    Data Assimilation: topics/dataassimilation.md
extra_css:
  - stylesheets/extra.css
plugins:
  - search
markdown_extensions:
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.arithmatex:
      generic: true
  - toc:
        permalink: ¶
extra_javascript:
  - javascripts/tablesort.min.js
  - javascripts/tablesort.js
  - javascripts/mathjax.js
  - javascripts/tex-mml-chtml.js
  - javascripts/polyfill.min.js
